apiVersion: v1
kind: Secret
metadata:
  name: task-manager-secrets
  namespace: task-management
type: Opaque
stringData:
  db-password: taskpassword
  jwt-secret: ZGV2LW9ubHktcGxhY2Vib2xkZXIta2V5LWNoYW5nZS1tZS1pbi1wcm9kdWN0aW9uIQ==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: task-manager-config
  namespace: task-management
data:
  SPRING_DATASOURCE_USERNAME: taskuser
  JWT_EXPIRATION: "86400000"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka/
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
